### ISSUE TITLE
Crash with MC 1.14.1

### ISSUE THREAD

**Issue by TimGoll** [Codasylph/CodaTech#3]
https://gist.github.com/TimGoll/70505fb755bd3d788f158379c8db05d0

your mod (version 1.14-1.0.2a)= crashes with MC 1.14.1, loader 147

**Comment by Codasylph** [comment]
That's not a huge surprise, there was a change from 1.14 to 1.14.1 that makes any mod with a block entity crash. The mod has not been updated to 1.14.1
